// <auto-generated />
using System;
using Garage2._0G6.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Garage2._0G6.Migrations
{
    [DbContext(typeof(Garage2_0G6Context))]
    [Migration("20210819090843_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Garage2._0G6.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Arrivaldate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Regnum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Wheel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Vehicle");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Arrivaldate = new DateTime(2021, 8, 19, 11, 8, 42, 564, DateTimeKind.Local).AddTicks(4041),
                            Brand = "Volvo",
                            Color = "red",
                            Model = "X3",
                            Regnum = "123ABC",
                            Type = "A",
                            Wheel = 4
                        },
                        new
                        {
                            Id = 2,
                            Arrivaldate = new DateTime(2021, 8, 19, 11, 8, 42, 567, DateTimeKind.Local).AddTicks(9474),
                            Brand = "Volvo",
                            Color = "red",
                            Model = "X3",
                            Regnum = "125ABC",
                            Type = "A",
                            Wheel = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
